global:
  scrape_interval: 500ms
  evaluation_interval: 15s
  scrape_timeout: 500ms

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "faust_app"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics